version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - hchauvin
  labels:
  - dependency
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: liquidjs
    versions:
    - 9.20.1
    - 9.21.0
    - 9.22.0
    - 9.22.1
    - 9.23.0
    - 9.23.1
    - 9.23.2
    - 9.23.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
